import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'fr' | 'en' | 'ko' | 'ja'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translations
const translations = {
  fr: {
    nav: {
      home: 'Accueil',
      about: 'À propos',
      projects: 'Projets',
      skills: 'Compétences',
      contact: 'Contact'
    },
    home: {
      welcome: 'BIENVENUE DANS MON PORTFOLIO',
      title: 'YOUSSEF GUERNIOU',
      subtitle: 'Administrateur Systèmes et Réseaux passionné par la cybersécurité et les technologies cloud. Spécialisé dans la gestion d\'infrastructures IT et la sécurisation des environnements numériques.',
      viewProjects: 'Voir mes projets',
      downloadCV: 'Télécharger CV',
      readyToCollaborate: 'Prêt à collaborer ?',
      collaborateText: 'Je suis toujours ouvert aux nouvelles opportunités et aux projets innovants. N\'hésitez pas à me contacter pour discuter de vos besoins.',
      getInTouch: 'Me contacter',
      viewMyWork: 'Voir mon travail',
      startProject: 'Démarrer un projet',
      viewGitHub: 'Voir GitHub'
    },
    about: {
      title: 'À PROPOS',
      subtitle: 'Passionné par la cybersécurité et l\'administration de systèmes, je transforme les défis techniques en opportunités d\'innovation. Mon objectif : sécuriser et optimiser les infrastructures numériques de demain.',
      myStory: 'Mon Histoire',
      storyText1: 'Tout a commencé par une curiosité naturelle pour comprendre comment fonctionnent les systèmes informatiques. De simple utilisateur, je suis devenu technicien support, puis administrateur systèmes et réseaux.',
      storyText2: 'Aujourd\'hui, je me spécialise en cybersécurité, un domaine qui combine parfaitement ma passion pour la technique et mon désir de protéger les organisations contre les menaces numériques.',
      myValues: 'Mes Valeurs',
      securityFirst: 'Sécurité Avant Tout',
      securityDesc: 'Protéger les systèmes et les données est ma priorité absolue. Chaque solution que je développe intègre les meilleures pratiques de cybersécurité.',
      continuousInnovation: 'Innovation Continue',
      innovationDesc: 'Je reste constamment à jour avec les dernières technologies et méthodologies pour offrir des solutions modernes et efficaces.',
      technicalExcellence: 'Excellence Technique',
      excellenceDesc: 'Je m\'efforce d\'atteindre l\'excellence dans chaque projet, en optimisant les performances et la fiabilité des systèmes.',
      collaboration: 'Collaboration',
      collaborationDesc: 'Je crois au travail d\'équipe et à la communication efficace pour réussir des projets complexes et ambitieux.',
      myJourney: 'Mon Parcours',
      journey2021: 'Début du Voyage',
      journey2021Desc: 'Premiers pas dans le support informatique chez BIOGROUP, découverte du monde professionnel IT.',
      journey2023: 'Évolution Technique',
      journey2023Desc: 'Passage à l\'administration systèmes et réseaux chez IMX France, montée en compétences techniques.',
      journey2024: 'Spécialisation Cybersécurité',
      journey2024Desc: 'Début du Master en Cybersécurité, approfondissement des connaissances en sécurité informatique.',
      journey2026: 'Objectif Futur',
      journey2026Desc: 'Expert en cybersécurité, consultant senior en sécurité des systèmes d\'information.'
    },
    projects: {
      showcase: 'MES PROJETS',
      title: 'Portfolio de Projets',
      subtitle: 'Découvrez mes réalisations en développement web et en gestion d\'infrastructures IT.',
      description: 'Description',
      features: 'FONCTIONNALITÉS PRINCIPALES',
      techStack: 'STACK TECHNOLOGIQUE',
      viewCode: 'VOIR LE CODE',
      viewLive: 'VOIR EN LIVE',
      wantToCollaborate: 'Envie de collaborer ?',
      collaborateText: 'Je suis toujours ouvert aux nouveaux projets et aux opportunités de collaboration.',
      startProject: 'Démarrer un projet',
      viewGitHub: 'Voir GitHub',
      // Projets spécifiques
      siemTitle: 'SIEM Security Onion - Cybersecurity Lab',
      siemDescription: 'Mise en place et configuration d\'un laboratoire de cybersécurité avec Security Onion, une plateforme SIEM open source. J\'ai déployé l\'infrastructure complète, configuré la surveillance réseau, et effectué des tests d\'intrusion pour valider l\'efficacité de la détection. Ce projet inclut l\'analyse de logs, la corrélation d\'événements, et la création de règles de détection personnalisées pour identifier les menaces avancées.',
      siemFeatures: {
        feature1: 'Déploiement et configuration de Security Onion',
        feature2: 'Tests d\'intrusion et simulation d\'attaques', 
        feature3: 'Création de règles de détection personnalisées',
        feature4: 'Réponse aux incidents de sécurité',
        feature5: 'Surveillance réseau en temps réel',
        feature6: 'Analyse de logs et corrélation d\'événements',
        feature7: 'Dashboard de visualisation des menaces'
      },
      glpiTitle: 'GLPI - Asset Management & Helpdesk',
      glpiDescription: 'Déploiement et configuration complète de GLPI (Gestionnaire Libre de Parc Informatique) pour la gestion des actifs IT et système de helpdesk. Mise en place d\'une solution centralisée pour l\'inventaire du matériel, la gestion des tickets, et le suivi des interventions. Configuration des workflows personnalisés, intégration avec l\'Active Directory, et formation des utilisateurs finaux.',
      glpiFeatures: {
        feature1: 'Installation et configuration de GLPI',
        feature2: 'Gestion complète de l\'inventaire IT',
        feature3: 'Système de tickets et helpdesk',
        feature4: 'Intégration Active Directory',
        feature5: 'Workflows ITIL personnalisés',
        feature6: 'Rapports et tableaux de bord',
        feature7: 'Formation des utilisateurs finaux'
      },
      portfolioTitle: 'Portfolio Website',
      portfolioDescription: 'Un site portfolio moderne avec une interface futuriste inspirée des interfaces AI. Développé avec React, TypeScript et Tailwind CSS, ce projet présente une expérience utilisateur immersive avec des animations fluides, un curseur personnalisé et un design cyberpunk sophistiqué. Le site inclut une introduction de hacking stylisée, une navigation intuitive, un système de traduction multilingue (FR/EN/KR/JP), des effets 3D CSS, des animations de scroll révélatrices, une horloge en temps réel, une barre de progression de scroll, et des boutons de copie interactifs pour email et téléphone avec feedback visuel.',
      portfolioFeatures: {
        feature1: 'Interface futuriste avec style AI et glassmorphism',
        feature2: 'Animation d\'introduction de hacking immersive',
        feature3: 'Curseur personnalisé interactif avec effets visuels',
        feature4: 'Système de traduction 4 langues (FR/EN/KR/JP)',
        feature5: 'Effets de profondeur CSS 3D et animations parallax',
        feature6: 'Animations de scroll révélatrices et transitions fluides',
        feature7: 'Horloge en temps réel avec localisation',
        feature8: 'Barre de progression de scroll minimaliste',
        feature9: 'Boutons de copie email/téléphone avec feedback',
        feature10: 'Design responsive et navigation mobile optimisée',
        feature11: 'Architecture composants modulaires et réutilisables',
        feature12: 'Gestion d\'état avec Context API React'
      }
    },
    skills: {
      expertise: 'EXPERTISE TECHNIQUE',
      title: 'Compétences & Technologies',
      subtitle: 'Un aperçu complet de mes compétences techniques, outils et expertise dans les domaines de l\'administration système, des réseaux et de la cybersécurité.',
      contactInfo: 'INFORMATIONS DE CONTACT',
      technicalSkills: 'COMPÉTENCES TECHNIQUES',
      softSkills: 'COMPÉTENCES TRANSVERSALES',
      experience: 'EXPÉRIENCES PROFESSIONNELLES',
      education: 'DIPLÔMES ET FORMATIONS',
      interests: 'CENTRES D\'INTÉRÊT',
      cloud: 'Cloud',
      networks: 'Réseaux',
      security: 'Sécurité',
      administration: 'Administration',
      monitoring: 'Monitoring',
      problemSolving: 'Résolution de problèmes',
      teamCollaboration: 'Collaboration en équipe',
      adaptability: 'Capacité d\'adaptation',
      systemAdmin: 'Administrateur Systèmes et Réseaux - ALTERNANCE',
      itSupport: 'Technicien support informatique',
      since2023: 'Depuis 2023',
      from2021to2023: 'De 2021 à 2023',
      masterCybersecurity: 'MASTERE - Cybersécurité',
      bachelorSystems: 'BACHELOR - Systèmes, Réseaux et Cloud',
      from2024to2026: 'De 2024 à 2026',
      from2023to2024: 'De 2023 à 2024',
      reading: 'Lecture',
      travel: 'Voyage',
      glpiDeployment: 'Déploiement de GLPI : Installation, configuration et gestion',
      firewallSetup: 'Mise en place de pare-feu et administration de l\'antivirus ESET',
      virtualization: 'Gestion d\'environnements virtualisés via vSphere / vCenter',
      nasMonitoring: 'Surveillance du réseau NAS avec SpaceObserver',
      vpnSetup: 'Installation et administration du VPN StormShield',
      gpoImplementation: 'Création et implémentation des GPO sur Active Directory',
      siemSetup: 'SIEM Security Onion: Déploiement, configuration et tests d\'intrusion',
      technicalSupport: 'Assistance et support technique du matériel informatique',
      ticketing: 'Organisation de travail par l\'intermédiaire d\'un service de ticketing',
      areas: ['Windows', 'Linux', 'DevOps', 'Cloud', 'Gestion de projet'],
      ipAddressing: 'Adressage IP',
      firewall: 'Pare-feux',
      vulnerabilityAnalysis: 'Analyse de vulnérabilités',
      windowsServer: 'Windows Server',
      linuxUbuntuDebian: 'Linux (Ubuntu, Debian)',
      englishLevel: 'Anglais - Niveau B2'
    },
    footer: {
      description: 'Administrateur Systèmes et Réseaux passionné par la cybersécurité, créant des expériences numériques innovantes. Construisons quelque chose d\'incroyable ensemble.'
    },
    contact: {
      title: 'Contact',
      subtitle: 'Contactez-moi',
      contactText: 'Je suis toujours ouvert aux nouvelles opportunités et aux projets innovants.',
      name: 'Nom',
      email: 'Email',
      message: 'Message',
      send: 'Envoyer',
      location: 'Paris, France',
      phone: '+33 6 20 01 95 27',
      emailAddress: 'youssef.guerniou@proton.me',
      copyEmail: 'Copier l\'email',
      emailCopied: 'Email copié !',
      copyPhone: 'Copier le téléphone',
      phoneCopied: 'Téléphone copié !',
      getInTouch: 'ENTRONS EN CONTACT',
      letsConnect: 'Connectons-nous',
      connectDescription: 'Prêt à démarrer un projet ou simplement discuter ? Je suis toujours excité d\'entendre parler de nouvelles opportunités et d\'idées intéressantes.',
      sendMessage: 'Envoyer un message',
      connectWithMe: 'Connectez-vous avec moi',
      quickStats: 'Statistiques rapides',
      projectsCompleted: 'Projets terminés',
      happyClients: 'Clients satisfaits',
      yearsExperience: 'Années d\'expérience',
      responseTime: 'Temps de réponse',
      skillsRadar: 'RADAR DE COMPÉTENCES',
      keyAchievements: 'RÉALISATIONS CLÉS',
      liveStatus: 'STATUT EN TEMPS RÉEL',
      funFacts: 'FAITS AMUSANTS',
      fact1: 'Le premier virus informatique a été créé en 1986 et s\'appelait "Brain"',
      factCategory: 'Histoire de la cybersécurité',
      coffeeConsumed: 'Cafés consommés',
      bugsToday: 'Bugs aujourd\'hui',
      funQuote: 'Le code est comme l\'humour. Quand il faut l\'expliquer, c\'est mauvais.',
      quoteAuthor: 'Cory House',
      dailyChallenge: 'Défi du jour',
      challengeText: 'Trouvez le bug caché dans cette page !',
      acceptChallenge: 'Accepter le défi',
      easterEgg: 'Cliquez pour une surprise !',
      // FAQ translations
      frequentlyAsked: 'QUESTIONS FRÉQUENTES',
      questions: 'QUESTIONS',
      faqServices: 'Quels services proposez-vous ?',
      faqServicesAnswer: 'Je propose une gestion complète d\'infrastructure IT, du conseil en cybersécurité, de l\'administration système et des services de sécurité réseau.',
      faqTimeline: 'Quel est votre délai typique de projet ?',
      faqTimelineAnswer: 'Les délais de projet varient selon la complexité. Les implémentations simples prennent 1-2 semaines, tandis que les projets d\'infrastructure complexes peuvent prendre 2-3 mois.',
      faqInternational: 'Travaillez-vous avec des clients internationaux ?',
      faqInternationalAnswer: 'Oui, je travaille avec des clients du monde entier. Je peux fournir un support et une consultation à distance pour les projets internationaux.',
      faqProcess: 'Quel est votre processus de développement ?',
      faqProcessAnswer: 'Mon processus inclut une consultation initiale, une analyse des exigences, une planification, une implémentation, des tests et un support continu.',
      readyToStart: 'Prêt à commencer ?',
      startDescription: 'Discutons de vos exigences de projet et créons quelque chose d\'incroyable ensemble.',
      startProject: 'Démarrer un projet',
      scheduleCall: 'Planifier un appel'
    }
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      projects: 'Projects',
      skills: 'Skills',
      contact: 'Contact'
    },
    home: {
      welcome: 'WELCOME TO MY PORTFOLIO',
      title: 'YOUSSEF GUERNIOU',
      subtitle: 'Systems and Network Administrator with expertise in cybersecurity and cloud technologies. Specializing in IT infrastructure management and digital environment security.',
      viewProjects: 'Explore my projects',
      downloadCV: 'Download Resume',
      readyToCollaborate: 'Let\'s work together',
      collaborateText: 'I welcome new opportunities and innovative projects. Please feel free to reach out to discuss your requirements.',
      getInTouch: 'Get in touch',
      viewMyWork: 'View my work',
      startProject: 'Start a project',
      viewGitHub: 'View GitHub'
    },
    about: {
      title: 'ABOUT',
      subtitle: 'Passionate about cybersecurity and system administration, I transform technical challenges into innovation opportunities. My goal: secure and optimize tomorrow\'s digital infrastructures.',
      myStory: 'My Story',
      storyText1: 'It all started with a natural curiosity to understand how computer systems work. From a simple user, I became a support technician, then a systems and network administrator.',
      storyText2: 'Today, I specialize in cybersecurity, a field that perfectly combines my passion for technology and my desire to protect organizations against digital threats.',
      myValues: 'My Values',
      securityFirst: 'Security First',
      securityDesc: 'Protecting systems and data is my absolute priority. Every solution I develop integrates cybersecurity best practices.',
      continuousInnovation: 'Continuous Innovation',
      innovationDesc: 'I constantly stay up to date with the latest technologies and methodologies to offer modern and efficient solutions.',
      technicalExcellence: 'Technical Excellence',
      excellenceDesc: 'I strive for excellence in every project, optimizing system performance and reliability.',
      collaboration: 'Collaboration',
      collaborationDesc: 'I believe in teamwork and effective communication to succeed in complex and ambitious projects.',
      myJourney: 'My Journey',
      journey2021: 'Beginning of the Journey',
      journey2021Desc: 'First steps in IT support at BIOGROUP, discovery of the professional IT world.',
      journey2023: 'Technical Evolution',
      journey2023Desc: 'Transition to systems and network administration at IMX France, technical skills development.',
      journey2024: 'Cybersecurity Specialization',
      journey2024Desc: 'Start of Master\'s in Cybersecurity, deepening knowledge in computer security.',
      journey2026: 'Future Goal',
      journey2026Desc: 'Cybersecurity expert, senior consultant in information systems security.'
    },
    projects: {
      showcase: 'MY PROJECTS',
      title: 'Project Portfolio',
      subtitle: 'Discover my achievements in web development and IT infrastructure management.',
      description: 'Description',
      features: 'MAIN FEATURES',
      techStack: 'TECHNOLOGY STACK',
      viewCode: 'VIEW CODE',
      viewLive: 'VIEW LIVE',
      wantToCollaborate: 'Interested in working together?',
      collaborateText: 'I welcome new projects and collaboration opportunities.',
      startProject: 'Start a project',
      viewGitHub: 'View GitHub',
      // Specific projects
      siemTitle: 'SIEM Security Onion - Cybersecurity Lab',
      siemDescription: 'Setup and configuration of a cybersecurity laboratory using Security Onion, an open-source SIEM platform. I deployed the complete infrastructure, configured network monitoring, and performed penetration testing to validate detection effectiveness. This project includes log analysis, event correlation, and creation of custom detection rules to identify advanced threats.',
      siemFeatures: {
        feature1: 'Security Onion deployment and configuration',
        feature2: 'Penetration testing and attack simulation',
        feature3: 'Custom detection rules creation',
        feature4: 'Security incident response',
        feature5: 'Real-time network monitoring',
        feature6: 'Log analysis and event correlation',
        feature7: 'Threat visualization dashboard'
      },
      glpiTitle: 'GLPI - Asset Management & Helpdesk',
      glpiDescription: 'Complete deployment and configuration of GLPI (Gestionnaire Libre de Parc Informatique) for IT asset management and helpdesk system. Implementation of a centralized solution for hardware inventory, ticket management, and intervention tracking. Custom workflow configuration, Active Directory integration, and end-user training.',
      glpiFeatures: {
        feature1: 'GLPI installation and configuration',
        feature2: 'Complete IT inventory management',
        feature3: 'Ticket system and helpdesk',
        feature4: 'Active Directory integration',
        feature5: 'Custom ITIL workflows',
        feature6: 'Reports and dashboards',
        feature7: 'End-user training'
      },
      portfolioTitle: 'Portfolio Website',
      portfolioDescription: 'A modern portfolio website with a futuristic interface inspired by AI interfaces. Developed with React, TypeScript and Tailwind CSS, this project provides an immersive user experience with smooth animations, custom cursor and sophisticated cyberpunk design. The site includes a stylized hacking intro, intuitive navigation, multilingual translation system (FR/EN/KR/JP), CSS 3D effects, scroll reveal animations, real-time clock, scroll progress bar, and interactive copy buttons for email and phone with visual feedback.',
      portfolioFeatures: {
        feature1: 'Futuristic interface with AI style and glassmorphism',
        feature2: 'Immersive hacking intro animation',
        feature3: 'Interactive custom cursor with visual effects',
        feature4: '4-language translation system (FR/EN/KR/JP)',
        feature5: 'CSS 3D depth effects and parallax animations',
        feature6: 'Scroll reveal animations and smooth transitions',
        feature7: 'Real-time clock with localization',
        feature8: 'Minimal scroll progress bar',
        feature9: 'Email/phone copy buttons with feedback',
        feature10: 'Responsive design and optimized mobile navigation',
        feature11: 'Modular and reusable component architecture',
        feature12: 'State management with Context API React'
      }
    },
    skills: {
      expertise: 'TECHNICAL EXPERTISE',
      title: 'Skills & Technologies',
      subtitle: 'A comprehensive overview of my technical skills, tools and expertise in system administration, networking and cybersecurity domains.',
      contactInfo: 'CONTACT INFORMATION',
      technicalSkills: 'TECHNICAL SKILLS',
      softSkills: 'SOFT SKILLS',
      experience: 'PROFESSIONAL EXPERIENCE',
      education: 'EDUCATION & TRAINING',
      interests: 'INTERESTS',
      cloud: 'Cloud',
      networks: 'Networks',
      security: 'Security',
      administration: 'Administration',
      monitoring: 'Monitoring',
      problemSolving: 'Problem Solving',
      teamCollaboration: 'Team Collaboration',
      adaptability: 'Adaptability',
      systemAdmin: 'Systems and Network Administrator - APPRENTICESHIP',
      itSupport: 'IT Support Technician',
      since2023: 'Since 2023',
      from2021to2023: 'From 2021 to 2023',
      masterCybersecurity: 'MASTER - Cybersecurity',
      bachelorSystems: 'BACHELOR - Systems, Networks and Cloud',
      from2024to2026: 'From 2024 to 2026',
      from2023to2024: 'From 2023 to 2024',
      reading: 'Reading',
      travel: 'Travel',
      glpiDeployment: 'GLPI deployment: Installation, configuration and management',
      firewallSetup: 'Firewall implementation and ESET antivirus administration',
      virtualization: 'Management of virtualized environments via vSphere / vCenter',
      nasMonitoring: 'NAS network monitoring with SpaceObserver',
      vpnSetup: 'Installation and administration of StormShield VPN',
      gpoImplementation: 'Creation and implementation of GPOs on Active Directory',
      siemSetup: 'SIEM Security Onion: Deployment, configuration and penetration testing',
      technicalSupport: 'Technical assistance and support for IT hardware',
      ticketing: 'Work organization via a ticketing service',
      areas: ['Windows', 'Linux', 'DevOps', 'Cloud', 'Project Management'],
      ipAddressing: 'IP Addressing',
      firewall: 'Firewall',
      vulnerabilityAnalysis: 'Vulnerability Analysis',
      windowsServer: 'Windows Server',
      linuxUbuntuDebian: 'Linux (Ubuntu, Debian)',
      englishLevel: 'English - Level B2'
    },
    footer: {
      description: 'Systems and Network Administrator passionate about cybersecurity, creating innovative digital experiences. Let\'s build something amazing together.'
    },
    contact: {
      title: 'Contact',
      subtitle: 'Contact me',
      contactText: 'I\'m always open to new opportunities and innovative projects.',
      name: 'Name',
      email: 'Email',
      message: 'Message',
      send: 'Send',
      location: 'Paris, France',
      phone: '+33 6 20 01 95 27',
      emailAddress: 'youssef.guerniou@proton.me',
      copyEmail: 'Copy email',
      emailCopied: 'Email copied!',
      copyPhone: 'Copy phone',
      phoneCopied: 'Phone copied!',
      getInTouch: 'GET IN TOUCH',
      letsConnect: 'Let\'s Connect',
      connectDescription: 'Ready to start a project or just want to chat? I\'m always excited to hear about new opportunities and interesting ideas.',
      sendMessage: 'Send a Message',
      connectWithMe: 'Connect With Me',
      quickStats: 'Quick Stats',
      projectsCompleted: 'Projects Completed',
      happyClients: 'Happy Clients',
      yearsExperience: 'Years Experience',
      responseTime: 'Response Time',
      skillsRadar: 'SKILLS RADAR',
      keyAchievements: 'KEY ACHIEVEMENTS',
      liveStatus: 'REAL-TIME STATUS',
      funFacts: 'FUN FACTS',
      fact1: 'The first computer virus was created in 1986 and was called "Brain"',
      factCategory: 'Cybersecurity History',
      coffeeConsumed: 'Cups of Coffee Consumed',
      bugsToday: 'Bugs Today',
      funQuote: 'Code is like humor. When it needs to explain itself, it\'s bad.',
      quoteAuthor: 'Cory House',
      dailyChallenge: 'Daily Challenge',
      challengeText: 'Find the hidden bug on this page!',
      acceptChallenge: 'Accept the Challenge',
      easterEgg: 'Click for a surprise!',
      // FAQ translations
      frequentlyAsked: 'FREQUENTLY ASKED',
      questions: 'QUESTIONS',
      faqServices: 'What services do you offer?',
      faqServicesAnswer: 'I offer comprehensive IT infrastructure management, cybersecurity consulting, system administration, and network security services.',
      faqTimeline: 'What is your typical project timeline?',
      faqTimelineAnswer: 'Project timelines vary depending on complexity. Simple implementations take 1-2 weeks, while complex infrastructure projects can take 2-3 months.',
      faqInternational: 'Do you work with international clients?',
      faqInternationalAnswer: 'Yes, I work with clients worldwide. I can provide remote support and consultation for international projects.',
      faqProcess: 'What is your development process?',
      faqProcessAnswer: 'My process includes initial consultation, requirements analysis, planning, implementation, testing, and ongoing support.',
      readyToStart: 'Ready to Start?',
      startDescription: 'Let\'s discuss your project requirements and create something amazing together.',
      startProject: 'Start a Project',
      scheduleCall: 'Schedule a Call'
    }
  },
  ko: {
    nav: {
      home: '홈',
      about: '소개',
      projects: '프로젝트',
      skills: '기술',
      contact: '연락처'
    },
    home: {
      welcome: '포트폴리오에 오신 것을 환영합니다',
      title: 'YOUSSEF GUERNIOU',
      subtitle: '사이버보안과 클라우드 기술 전문성을 보유한 시스템 네트워크 관리자입니다. IT 인프라 관리 및 디지털 환경 보안을 전문으로 합니다.',
      viewProjects: '프로젝트 살펴보기',
      downloadCV: '이력서 다운로드',
      readyToCollaborate: '함께 일하실까요',
      collaborateText: '새로운 기회와 혁신적인 프로젝트에 항상 열려있습니다. 필요하신 사항에 대해 언제든지 문의해 주시기 바랍니다.',
      getInTouch: '연락하기',
      viewMyWork: '작업 살펴보기',
      startProject: '프로젝트 시작하기',
      viewGitHub: 'GitHub 보기'
    },
    about: {
      title: '소개',
      subtitle: '사이버보안과 시스템 관리에 열정을 가지고 기술적 도전을 혁신의 기회로 만들어갑니다. 목표는 미래의 디지털 인프라를 보호하고 최적화하는 것입니다.',
      myStory: '저의 이야기',
      storyText1: '컴퓨터 시스템의 작동 원리에 대한 자연스러운 호기심에서 시작되었습니다. 일반 사용자에서 기술 지원 담당자로, 그리고 시스템 및 네트워크 관리자로 성장해왔습니다.',
      storyText2: '현재는 사이버보안을 전문 분야로 하고 있으며, 이는 기술에 대한 열정과 조직을 디지털 위협으로부터 보호하고자 하는 목표를 완벽하게 결합한 분야입니다.',
      myValues: '내 가치관',
      securityFirst: '보안 우선',
      securityDesc: '시스템과 데이터 보호를 최우선으로 합니다. 개발하는 모든 솔루션에 사이버보안 모범 사례를 적용합니다.',
      continuousInnovation: '지속적 혁신',
      innovationDesc: '현대적이고 효율적인 솔루션 제공을 위해 최신 기술과 방법론을 지속적으로 학습하고 적용합니다.',
      technicalExcellence: '기술적 우수성',
      excellenceDesc: '모든 프로젝트에서 기술적 우수성을 추구하며, 시스템 성능과 신뢰성 최적화에 집중합니다.',
      collaboration: '협업',
      collaborationDesc: '복잡하고 도전적인 프로젝트의 성공을 위해 팀워크와 효과적인 커뮤니케이션을 중요하게 생각합니다.',
      myJourney: '내 여정',
      journey2021: '여정의 시작',
      journey2021Desc: 'BIOGROUP에서 IT 지원의 첫 걸음, 전문 IT 세계의 발견。',
      journey2023: '기술적 진화',
      journey2023Desc: 'IMX France에서 시스템 및 네트워크 관리로 전환, 기술적 역량 개발。',
      journey2024: '사이버보안 전문화',
      journey2024Desc: '사이버보안 석사 시작, 컴퓨터 보안 지식 심화。',
      journey2026: '미래 목표',
      journey2026Desc: '사이버보안 전문가, 정보 시스템 보안 시니어 컨설턴트。'
    },
    projects: {
      showcase: '내 프로젝트',
      title: '프로젝트 포트폴리오',
      subtitle: '웹 개발 및 IT 인프라 관리에서의 성과를 확인하세요。',
      description: '설명',
      features: '주요 기능',
      techStack: '기술 스택',
      viewCode: '코드 보기',
      viewLive: '실시간 보기',
      wantToCollaborate: '협업하고 싶으신가요？',
      collaborateText: '저는 항상 새로운 프로젝트와 협업 기회에 열려있습니다。',
      startProject: '프로젝트 시작',
      viewGitHub: 'GitHub 보기',
      // 구체적인 프로젝트들
      siemTitle: 'SIEM Security Onion - 사이버보안 랩',
      siemDescription: 'Security Onion(오픈소스 SIEM 플랫폼)을 사용한 사이버보안 랩 구축 및 설정. 전체 인프라를 배포하고 네트워크 모니터링을 구성했으며, 침입 테스트를 수행하여 탐지 효과를 검증했습니다.',
      siemFeatures: {
        feature1: 'Security Onion 배포 및 구성',
        feature2: '침입 테스트 및 공격 시뮬레이션',
        feature3: '맞춤형 탐지 규칙 생성',
        feature4: '보안 인시던트 대응',
        feature5: '실시간 네트워크 모니터링',
        feature6: '로그 분석 및 이벤트 상관관계',
        feature7: '위협 시각화 대시보드'
      },
      glpiTitle: 'GLPI - 자산 관리 및 헬프데스크',
      glpiDescription: 'IT 자산 관리 및 헬프데스크 시스템을 위한 GLPI 완전 배포 및 구성. 하드웨어 인벤토리, 티켓 관리를 위한 중앙 집중식 솔루션 구현.',
      glpiFeatures: {
        feature1: 'GLPI 설치 및 구성',
        feature2: '완전한 IT 인벤토리 관리',
        feature3: '티켓 시스템 및 헬프데스크',
        feature4: 'Active Directory 통합',
        feature5: '맞춤형 ITIL 워크플로',
        feature6: '리포트 및 대시보드',
        feature7: '최종 사용자 교육'
      },
      portfolioTitle: '포트폴리오 웹사이트',
      portfolioDescription: 'AI 인터페이스에서 영감을 받은 미래형 포트폴리오 사이트. React, TypeScript, Tailwind CSS로 개발된 몰입형 사용자 경험.',
      portfolioFeatures: {
        feature1: 'AI 스타일 미래형 인터페이스',
        feature2: '몰입형 해킹 인트로 애니메이션',
        feature3: '대화형 맞춤 커서',
        feature4: '4개 언어 번역 시스템',
        feature5: 'CSS 3D 및 패럴랙스 효과',
        feature6: '스크롤 공개 애니메이션',
        feature7: '실시간 시계',
        feature8: '스크롤 진행률 바',
        feature9: '이메일/전화 복사 버튼',
        feature10: '반응형 모바일 디자인',
        feature11: '모듈식 컴포넌트 아키텍처',
        feature12: 'Context API 상태 관리'
      }
    },
    skills: {
      expertise: '기술 전문성',
      title: '기술 및 도구',
      subtitle: '시스템 관리, 네트워킹 및 사이버보안 분야에서의 기술적 역량, 도구 및 전문성에 대한 포괄적인 개요。',
      contactInfo: '연락처 정보',
      technicalSkills: '기술적 역량',
      softSkills: '소프트 스킬',
      experience: '전문 경험',
      education: '교육 및 훈련',
      interests: '관심사',
      cloud: '클라우드',
      networks: '네트워크',
      security: '보안',
      administration: '관리',
      monitoring: '모니터링',
      problemSolving: '문제 해결',
      teamCollaboration: '팀 협업',
      adaptability: '적응력',
      systemAdmin: '시스템 및 네트워크 관리자 - 견습',
      itSupport: 'IT 지원 기술자',
      since2023: '2023년부터',
      from2021to2023: '2021년부터 2023년까지',
      masterCybersecurity: '석사 - 사이버보안',
      bachelorSystems: '학사 - 시스템, 네트워크 및 클라우드',
      from2024to2026: '2024년부터 2026년까지',
      from2023to2024: '2023년부터 2024년까지',
      reading: '독서',
      travel: '여행',
      glpiDeployment: 'GLPI 배포: 설치, 구성 및 관리',
      firewallSetup: '방화벽 구현 및 ESET 바이러스 백신 관리',
      virtualization: 'vSphere / vCenter를 통한 가상화 환경 관리',
      nasMonitoring: 'SpaceObserver를 사용한 NAS 네트워크 모니터링',
      vpnSetup: 'StormShield VPN 설치 및 관리',
      gpoImplementation: 'Active Directory에서 GPO 생성 및 구현',
      siemSetup: 'SIEM 구현: Security Onion',
      technicalSupport: 'IT 하드웨어 기술 지원 및 지원',
      ticketing: '티켓팅 서비스를 통한 작업 조직',
      areas: ['Windows', 'Linux', 'DevOps', 'Cloud', '프로젝트 관리'],
      ipAddressing: 'IP 주소 지정',
      firewall: '방화벽',
      vulnerabilityAnalysis: '취약점 분석',
      windowsServer: 'Windows Server',
      linuxUbuntuDebian: 'Linux (Ubuntu, Debian)',
      englishLevel: '영어 - B2 레벨'
    },
    footer: {
      description: '사이버보안에 열정을 가진 시스템 네트워크 관리자로, 혁신적인 디지털 경험을 만들어갑니다. 함께 멋진 것을 만들어봅시다.'
    },
    contact: {
      title: '연락처',
      subtitle: '연락하기',
      contactText: '저는 항상 새로운 기회와 혁신적인 프로젝트에 열려있습니다。',
      name: '이름',
      email: '이메일',
      message: '메시지',
      send: '보내기',
      location: '파리, 프랑스',
      phone: '+33 6 20 01 95 27',
      emailAddress: 'youssef.guerniou@proton.me',
      copyEmail: '이메일 복사',
      emailCopied: '이메일 복사됨!',
      copyPhone: '전화번호 복사',
      phoneCopied: '전화번호 복사됨!',
      getInTouch: '연락하기',
      letsConnect: '연결해봅시다',
      connectDescription: '프로젝트를 시작하거나 단순히 대화하고 싶으신가요？저는 항상 새로운 기회와 흥미로운 아이디어에 대해 듣는 것을 기대합니다。',
      sendMessage: '메시지 보내기',
      connectWithMe: '저와 연결하기',
      quickStats: '빠른 통계',
      projectsCompleted: '완료된 프로젝트',
      happyClients: '만족한 고객',
      yearsExperience: '경험 연수',
      responseTime: '응답 시간',
      skillsRadar: '기술 레이더',
      keyAchievements: '주요 성과',
      liveStatus: '실시간 상태',
      funFacts: '재미있는 사실',
      fact1: '최초의 컴퓨터 바이러스는 1986년에 생성되었으며 "Brain"이라고 불렸습니다',
      factCategory: '사이버보안 역사',
      coffeeConsumed: '소비된 커피',
      bugsToday: '오늘의 버그',
      funQuote: '코드는 유머와 같습니다。스스로 설명해야 할 때는 나쁜 것입니다。',
      quoteAuthor: 'Cory House',
      dailyChallenge: '일일 도전',
      challengeText: '이 페이지에서 숨겨진 버그를 찾아보세요！',
      acceptChallenge: '도전 수락',
      easterEgg: '클릭하면 놀라움이！',
      // FAQ translations
      frequentlyAsked: '자주 묻는 질문',
      questions: '질문',
      faqServices: '어떤 서비스를 제공하시나요?',
      faqServicesAnswer: '포괄적인 IT 인프라 관리, 사이버보안 컨설팅, 시스템 관리 및 네트워크 보안 서비스를 제공합니다.',
      faqTimeline: '일반적인 프로젝트 일정은 어떻게 되나요?',
      faqTimelineAnswer: '프로젝트 일정은 복잡성에 따라 다릅니다. 간단한 구현은 1-2주, 복잡한 인프라 프로젝트는 2-3개월이 걸릴 수 있습니다.',
      faqInternational: '국제 고객과 함께 일하시나요?',
      faqInternationalAnswer: '네, 전 세계 고객과 함께 일합니다. 국제 프로젝트에 대한 원격 지원 및 컨설팅을 제공할 수 있습니다.',
      faqProcess: '개발 프로세스는 어떻게 되나요?',
      faqProcessAnswer: '제 프로세스는 초기 상담, 요구사항 분석, 계획, 구현, 테스트 및 지속적인 지원을 포함합니다.',
      readyToStart: '시작할 준비가 되셨나요?',
      startDescription: '프로젝트 요구사항에 대해 논의하고 함께 놀라운 것을 만들어봅시다.',
      startProject: '프로젝트 시작',
      scheduleCall: '통화 예약'
    }
  },
  ja: {
    nav: {
      home: 'ホーム',
      about: '自己紹介',
      projects: 'プロジェクト',
      skills: 'スキル',
      contact: 'お問い合わせ'
    },
    home: {
      welcome: 'ポートフォリオをご覧いただき、ありがとうございます',
      title: 'YOUSSEF GUERNIOU',
      subtitle: 'サイバーセキュリティとクラウド技術を専門とするシステム・ネットワーク管理者です。ITインフラ管理とデジタル環境のセキュリティに従事しております。',
      viewProjects: 'プロジェクト一覧',
      downloadCV: '履歴書ダウンロード',
      readyToCollaborate: 'お仕事のご相談をお待ちしております',
      collaborateText: '新しい機会や革新的なプロジェクトについて、常にご相談をお受けしております。ご要望がございましたら、お気軽にお問い合わせください。',
      getInTouch: 'お問い合わせ',
      viewMyWork: '実績を見る',
      startProject: 'プロジェクト開始',
      viewGitHub: 'GitHub'
    },
    about: {
      title: '自己紹介',
      subtitle: 'サイバーセキュリティとシステム管理に情熱を持つ私は、技術的課題を革新の機会に変えます。目標：明日のデジタルインフラを保護し最適化すること。',
      myStory: '私の物語',
      storyText1: 'コンピュータシステムがどのように動作するかを理解したいという自然な好奇心から始まりました。単純なユーザーからサポート技術者になり、その後システム・ネットワーク管理者になりました。',
      storyText2: '今日、私はサイバーセキュリティを専門としており、これは技術への情熱と組織をデジタル脅威から保護したいという願望を完璧に組み合わせた分野です。',
      myValues: '私の価値観',
      securityFirst: 'セキュリティ第一',
      securityDesc: 'システムとデータを保護することが私の絶対的な優先事項です。私が開発するすべてのソリューションはサイバーセキュリティのベストプラクティスを統合しています。',
      continuousInnovation: '継続的革新',
      innovationDesc: '私は現代的で効率的なソリューションを提供するために、最新の技術と方法論を常に更新しています。',
      technicalExcellence: '技術的卓越性',
      excellenceDesc: '私はすべてのプロジェクトで卓越性を追求し、システムのパフォーマンスと信頼性を最適化します。',
      collaboration: 'コラボレーション',
      collaborationDesc: '私は複雑で野心的なプロジェクトで成功するために、チームワークと効果的なコミュニケーションを信じています。',
      myJourney: '私の旅',
      journey2021: '旅の始まり',
      journey2021Desc: 'BIOGROUPでのITサポートの第一歩、専門IT世界の発見。',
      journey2023: '技術的進化',
      journey2023Desc: 'IMX Franceでのシステム・ネットワーク管理への移行、技術的スキルの開発。',
      journey2024: 'サイバーセキュリティ専門化',
      journey2024Desc: 'サイバーセキュリティ修士課程開始、コンピュータセキュリティ知識の深化。',
      journey2026: '将来の目標',
      journey2026Desc: 'サイバーセキュリティ専門家、情報システムセキュリティシニアコンサルタント。'
    },
    projects: {
      showcase: '私のプロジェクト',
      title: 'プロジェクトポートフォリオ',
      subtitle: 'ウェブ開発とITインフラ管理での成果をご覧ください。',
      description: '説明',
      features: '主要機能',
      techStack: '技術スタック',
      viewCode: 'コードを見る',
      viewLive: 'ライブで見る',
      wantToCollaborate: 'ご一緒にお仕事をいたしませんか',
      collaborateText: '新しいプロジェクトやコラボレーションの機会を常にお待ちしております。',
      startProject: 'プロジェクト開始',
      viewGitHub: 'GitHubを見る',
      // 具体的なプロジェクト
      siemTitle: 'SIEM Security Onion - サイバーセキュリティ ラボ',
      siemDescription: 'オープンソースのSIEMプラットフォームであるSecurity Onionを使用したサイバーセキュリティラボの構築と設定。完全なインフラストラクチャを展開し、ネットワーク監視を設定し、検出効果を検証するための侵入テストを実施いたしました。このプロジェクトには、ログ分析、イベント相関、高度な脅威を特定するためのカスタム検出ルールの作成が含まれます。',
      siemFeatures: {
        feature1: 'Security Onionの展開と設定',
        feature2: '侵入テストと攻撃シミュレーション',
        feature3: 'カスタム検出ルールの作成',
        feature4: 'セキュリティインシデント対応',
        feature5: 'リアルタイムネットワーク監視',
        feature6: 'ログ分析とイベント相関',
        feature7: '脅威可視化ダッシュボード'
      },
      glpiTitle: 'GLPI - 資産管理・ヘルプデスク',
      glpiDescription: 'IT資産管理とヘルプデスクシステムのためのGLPI（Gestionnaire Libre de Parc Informatique）の完全な展開と設定。ハードウェアインベントリ、チケット管理、介入追跡のための中央集権的ソリューションの実装。カスタムワークフロー設定、Active Directory統合、エンドユーザートレーニング。',
      glpiFeatures: {
        feature1: 'GLPIのインストールと設定',
        feature2: '完全なITインベントリ管理',
        feature3: 'チケットシステムとヘルプデスク',
        feature4: 'Active Directory統合',
        feature5: 'カスタムITILワークフロー',
        feature6: 'レポートとダッシュボード',
        feature7: 'エンドユーザートレーニング'
      },
      portfolioTitle: 'ポートフォリオウェブサイト',
      portfolioDescription: 'AIインターフェースからインスピレーションを得た未来的なインターフェースを持つ現代的なポートフォリオサイト。React、TypeScript、Tailwind CSSで開発されたこのプロジェクトは、滑らかなアニメーション、カスタムカーソル、洗練されたサイバーパンクデザインで没入感のあるユーザー体験を提供します。スタイライズされたハッキングイントロ、直感的なナビゲーション、多言語翻訳システム（FR/EN/KR/JP）、CSS 3Dエフェクト、スクロール表示アニメーション、リアルタイム時計、スクロール進行バー、視覚的フィードバック付きメール・電話コピーボタンが含まれています。',
      portfolioFeatures: {
        feature1: 'AIスタイルとグラスモーフィズムを使用した未来的インターフェース',
        feature2: '没入感のあるハッキングイントロアニメーション',
        feature3: '視覚効果付きインタラクティブカスタムカーソル',
        feature4: '4言語翻訳システム（FR/EN/KR/JP）',
        feature5: 'CSS 3D深度エフェクトとパララックスアニメーション',
        feature6: 'スクロール表示アニメーションと滑らかなトランジション',
        feature7: 'ローカライゼーション付きリアルタイム時計',
        feature8: 'ミニマルなスクロール進行バー',
        feature9: 'フィードバック付きメール・電話コピーボタン',
        feature10: 'レスポンシブデザインと最適化されたモバイルナビゲーション',
        feature11: 'モジュラーで再利用可能なコンポーネントアーキテクチャ',
        feature12: 'Context API Reactによる状態管理'
      }
    },
    skills: {
      expertise: '技術専門性',
      title: 'スキルと技術',
      subtitle: 'システム管理、ネットワーキング、サイバーセキュリティ分野での技術的スキル、ツール、専門性の包括的概要。',
      contactInfo: '連絡先情報',
      technicalSkills: '技術的スキル',
      softSkills: 'ソフトスキル',
      experience: '専門経験',
      education: '教育と訓練',
      interests: '興味',
      cloud: 'クラウド',
      networks: 'ネットワーク',
      security: 'セキュリティ',
      administration: '管理',
      monitoring: 'モニタリング',
      problemSolving: '問題解決',
      teamCollaboration: 'チームコラボレーション',
      adaptability: '適応性',
      systemAdmin: 'システム・ネットワーク管理者 - 見習い',
      itSupport: 'ITサポート技術者',
      since2023: '2023年から',
      from2021to2023: '2021年から2023年まで',
      masterCybersecurity: '修士 - サイバーセキュリティ',
      bachelorSystems: '学士 - システム、ネットワーク、クラウド',
      from2024to2026: '2024年から2026年まで',
      from2023to2024: '2023年から2024年まで',
      reading: '読書',
      travel: '旅行',
      glpiDeployment: 'GLPI展開：インストール、設定、管理',
      firewallSetup: 'ファイアウォール実装とESETアンチウイルス管理',
      virtualization: 'vSphere / vCenterによる仮想化環境管理',
      nasMonitoring: 'SpaceObserverによるNASネットワーク監視',
      vpnSetup: 'StormShield VPNのインストールと管理',
      gpoImplementation: 'Active DirectoryでのGPO作成と実装',
      siemSetup: 'SIEM実装：Security Onion',
      technicalSupport: 'ITハードウェアの技術支援とサポート',
      ticketing: 'チケットサービスによる作業組織化',
      areas: ['Windows', 'Linux', 'DevOps', 'Cloud', 'プロジェクト管理'],
      ipAddressing: 'IPアドレッシング',
      firewall: 'ファイアウォール',
      vulnerabilityAnalysis: '脆弱性分析',
      windowsServer: 'Windows Server',
      linuxUbuntuDebian: 'Linux (Ubuntu, Debian)',
      englishLevel: '英語 - B2レベル'
    },
    footer: {
      description: 'サイバーセキュリティに情熱を持つシステム・ネットワーク管理者で、革新的なデジタル体験を創造しております。一緒に素晴らしいものを作りましょう。'
    },
    contact: {
      title: 'お問い合わせ',
      subtitle: 'お問い合わせ',
      contactText: '私は常に新しい機会と革新的なプロジェクトにオープンです。',
      name: '名前',
      email: 'メール',
      message: 'メッセージ',
      send: '送信',
      location: 'パリ、フランス',
      phone: '+33 6 20 01 95 27',
      emailAddress: 'youssef.guerniou@proton.me',
      copyEmail: 'メールをコピー',
      emailCopied: 'メールをコピーしました！',
      copyPhone: '電話番号をコピー',
      phoneCopied: '電話番号をコピーしました！',
      getInTouch: 'お問い合わせ',
      letsConnect: 'つながりましょう',
      connectDescription: 'プロジェクトを始める準備ができているか、単に話したいだけですか？私は常に新しい機会と興味深いアイデアについて聞くことを楽しみにしています。',
      sendMessage: 'メッセージを送る',
      connectWithMe: '私とつながる',
      quickStats: 'クイック統計',
      projectsCompleted: '完了したプロジェクト',
      happyClients: '満足したクライアント',
      yearsExperience: '経験年数',
      responseTime: '応答時間',
      skillsRadar: 'スキルレーダー',
      keyAchievements: '主要な成果',
      liveStatus: 'リアルタイムステータス',
      funFacts: '面白い事実',
      fact1: '最初のコンピュータウイルスは1986年に作成され、「Brain」と呼ばれていました',
      factCategory: 'サイバーセキュリティの歴史',
      coffeeConsumed: '消費されたコーヒー',
      bugsToday: '今日のバグ',
      funQuote: 'コードはユーモアのようなものです。自分自身を説明する必要があるときは悪いものです。',
      quoteAuthor: 'Cory House',
      dailyChallenge: '日々の挑戦',
      challengeText: 'このページで隠されたバグを見つけてください！',
      acceptChallenge: '挑戦を受け入れる',
      easterEgg: 'クリックすると驚きが！',
      // FAQ translations
      frequentlyAsked: 'よくある質問',
      questions: '質問',
      faqServices: 'どのようなサービスを提供していますか？',
      faqServicesAnswer: '包括的なITインフラ管理、サイバーセキュリティコンサルティング、システム管理、ネットワークセキュリティサービスを提供しています。',
      faqTimeline: '一般的なプロジェクトのタイムラインはどのくらいですか？',
      faqTimelineAnswer: 'プロジェクトのタイムラインは複雑さによって異なります。簡単な実装は1-2週間、複雑なインフラプロジェクトは2-3ヶ月かかる場合があります。',
      faqInternational: '国際的なクライアントと一緒に仕事をしていますか？',
      faqInternationalAnswer: 'はい、世界中のクライアントと一緒に仕事をしています。国際プロジェクトのリモートサポートとコンサルティングを提供できます。',
      faqProcess: '開発プロセスはどのようになっていますか？',
      faqProcessAnswer: '私のプロセスは初期コンサルテーション、要件分析、計画、実装、テスト、継続的なサポートを含みます。',
      readyToStart: '始める準備はできていますか？',
      startDescription: 'プロジェクトの要件について話し合い、一緒に素晴らしいものを作りましょう。',
      startProject: 'プロジェクト開始',
      scheduleCall: '通話予約'
    }
  }
}

interface LanguageProviderProps {
  children: ReactNode
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr')

  const t = (key: string): string => {
    const keys = key.split('.')
    let value: any = translations[language]
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k]
      } else {
        return key // Return the key if translation not found
      }
    }
    
    return typeof value === 'string' ? value : key
  }

  const value = {
    language,
    setLanguage,
    t
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 