import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'fr' | 'en' | 'ko' | 'ja'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Translations
const translations = {
  fr: {
    nav: {
      home: 'Accueil',
      about: 'À propos',
      projects: 'Projets',
      skills: 'Compétences',
      contact: 'Contact'
    },
    home: {
      welcome: 'BIENVENUE DANS MON PORTFOLIO',
      title: 'YOUSSEF GUERNIOU',
      subtitle: 'Administrateur Systèmes et Réseaux passionné par la cybersécurité et les technologies cloud. Spécialisé dans la gestion d\'infrastructures IT et la sécurisation des environnements numériques.',
      viewProjects: 'Voir mes projets',
      downloadCV: 'Télécharger CV',
      readyToCollaborate: 'Prêt à collaborer ?',
      collaborateText: 'Je suis toujours ouvert aux nouvelles opportunités et aux projets innovants. N\'hésitez pas à me contacter pour discuter de vos besoins.',
      getInTouch: 'Me contacter',
      viewMyWork: 'Voir mon travail',
      startProject: 'Démarrer un projet',
      viewGitHub: 'Voir GitHub'
    },
    about: {
      title: 'À PROPOS',
      subtitle: 'Passionné par la cybersécurité et l\'administration de systèmes, je transforme les défis techniques en opportunités d\'innovation. Mon objectif : sécuriser et optimiser les infrastructures numériques de demain.',
      myStory: 'Mon Histoire',
      storyText1: 'Tout a commencé par une curiosité naturelle pour comprendre comment fonctionnent les systèmes informatiques. De simple utilisateur, je suis devenu technicien support, puis administrateur systèmes et réseaux.',
      storyText2: 'Aujourd\'hui, je me spécialise en cybersécurité, un domaine qui combine parfaitement ma passion pour la technique et mon désir de protéger les organisations contre les menaces numériques.',
      myValues: 'Mes Valeurs',
      securityFirst: 'Sécurité Avant Tout',
      securityDesc: 'Protéger les systèmes et les données est ma priorité absolue. Chaque solution que je développe intègre les meilleures pratiques de cybersécurité.',
      continuousInnovation: 'Innovation Continue',
      innovationDesc: 'Je reste constamment à jour avec les dernières technologies et méthodologies pour offrir des solutions modernes et efficaces.',
      technicalExcellence: 'Excellence Technique',
      excellenceDesc: 'Je m\'efforce d\'atteindre l\'excellence dans chaque projet, en optimisant les performances et la fiabilité des systèmes.',
      collaboration: 'Collaboration',
      collaborationDesc: 'Je crois au travail d\'équipe et à la communication efficace pour réussir des projets complexes et ambitieux.',
      myJourney: 'Mon Parcours',
      journey2021: 'Début du Voyage',
      journey2021Desc: 'Premiers pas dans le support informatique chez BIOGROUP, découverte du monde professionnel IT.',
      journey2023: 'Évolution Technique',
      journey2023Desc: 'Passage à l\'administration systèmes et réseaux chez IMX France, montée en compétences techniques.',
      journey2024: 'Spécialisation Cybersécurité',
      journey2024Desc: 'Début du Master en Cybersécurité, approfondissement des connaissances en sécurité informatique.',
      journey2026: 'Objectif Futur',
      journey2026Desc: 'Expert en cybersécurité, consultant senior en sécurité des systèmes d\'information.'
    },
    projects: {
      showcase: 'MES PROJETS',
      title: 'Portfolio de Projets',
      subtitle: 'Découvrez mes réalisations en développement web et en gestion d\'infrastructures IT.',
      description: 'Description',
      features: 'FONCTIONNALITÉS PRINCIPALES',
      techStack: 'STACK TECHNOLOGIQUE',
      viewCode: 'VOIR LE CODE',
      viewLive: 'VOIR EN LIVE',
      wantToCollaborate: 'Envie de collaborer ?',
      collaborateText: 'Je suis toujours ouvert aux nouveaux projets et aux opportunités de collaboration.',
      startProject: 'Démarrer un projet',
      viewGitHub: 'Voir GitHub'
    },
    skills: {
      expertise: 'EXPERTISE TECHNIQUE',
      title: 'Compétences & Technologies',
      subtitle: 'Un aperçu complet de mes compétences techniques, outils et expertise dans les domaines de l\'administration système, des réseaux et de la cybersécurité.',
      contactInfo: 'INFORMATIONS DE CONTACT',
      technicalSkills: 'COMPÉTENCES TECHNIQUES',
      softSkills: 'COMPÉTENCES TRANSVERSALES',
      experience: 'EXPÉRIENCES PROFESSIONNELLES',
      education: 'DIPLÔMES ET FORMATIONS',
      interests: 'CENTRES D\'INTÉRÊT',
      cloud: 'Cloud',
      networks: 'Réseaux',
      security: 'Sécurité',
      administration: 'Administration',
      monitoring: 'Monitoring',
      problemSolving: 'Résolution de problèmes',
      teamCollaboration: 'Collaboration en équipe',
      adaptability: 'Capacité d\'adaptation',
      systemAdmin: 'Administrateur Systèmes et Réseaux - ALTERNANCE',
      itSupport: 'Technicien support informatique',
      since2023: 'Depuis 2023',
      from2021to2023: 'De 2021 à 2023',
      masterCybersecurity: 'MASTERE - Cybersécurité',
      bachelorSystems: 'BACHELOR - Systèmes, Réseaux et Cloud',
      from2024to2026: 'De 2024 à 2026',
      from2023to2024: 'De 2023 à 2024',
      reading: 'Lecture',
      travel: 'Voyage',
      glpiDeployment: 'Déploiement de GLPI : Installation, configuration et gestion',
      firewallSetup: 'Mise en place de pare-feu et administration de l\'antivirus ESET',
      virtualization: 'Gestion d\'environnements virtualisés via vSphere / vCenter',
      nasMonitoring: 'Surveillance du réseau NAS avec SpaceObserver',
      vpnSetup: 'Installation et administration du VPN StormShield',
      gpoImplementation: 'Création et implémentation des GPO sur Active Directory',
      siemSetup: 'Mise en place d\'un SIEM: Security Onion',
      technicalSupport: 'Assistance et support technique du matériel informatique',
      ticketing: 'Organisation de travail par l\'intermédiaire d\'un service de ticketing',
      areas: ['Windows', 'Linux', 'DevOps', 'Cloud', 'Gestion de projet'],
      ipAddressing: 'Adressage IP',
      firewall: 'Pare-feux',
      vulnerabilityAnalysis: 'Analyse de vulnérabilités',
      windowsServer: 'Windows Server',
      linuxUbuntuDebian: 'Linux (Ubuntu, Debian)',
      englishLevel: 'Anglais - Niveau B2'
    },
    contact: {
      title: 'Contact',
      subtitle: 'Contactez-moi',
      contactText: 'Je suis toujours ouvert aux nouvelles opportunités et aux projets innovants.',
      name: 'Nom',
      email: 'Email',
      message: 'Message',
      send: 'Envoyer',
      location: 'Paris, France',
      phone: '+33 6 20 01 95 27',
      emailAddress: 'youssef.guerniou@proton.me',
      getInTouch: 'ENTRONS EN CONTACT',
      letsConnect: 'Connectons-nous',
      connectDescription: 'Prêt à démarrer un projet ou simplement discuter ? Je suis toujours excité d\'entendre parler de nouvelles opportunités et d\'idées intéressantes.',
      sendMessage: 'Envoyer un message',
      connectWithMe: 'Connectez-vous avec moi',
      quickStats: 'Statistiques rapides',
      projectsCompleted: 'Projets terminés',
      happyClients: 'Clients satisfaits',
      yearsExperience: 'Années d\'expérience',
      responseTime: 'Temps de réponse',
      skillsRadar: 'RADAR DE COMPÉTENCES',
      keyAchievements: 'RÉALISATIONS CLÉS',
      liveStatus: 'STATUT EN TEMPS RÉEL',
      funFacts: 'FAITS AMUSANTS',
      fact1: 'Le premier virus informatique a été créé en 1986 et s\'appelait "Brain"',
      factCategory: 'Histoire de la cybersécurité',
      coffeeConsumed: 'Cafés consommés',
      bugsToday: 'Bugs aujourd\'hui',
      funQuote: 'Le code est comme l\'humour. Quand il faut l\'expliquer, c\'est mauvais.',
      quoteAuthor: 'Cory House',
      dailyChallenge: 'Défi du jour',
      challengeText: 'Trouvez le bug caché dans cette page !',
      acceptChallenge: 'Accepter le défi',
      easterEgg: 'Cliquez pour une surprise !',
      // FAQ translations
      frequentlyAsked: 'QUESTIONS FRÉQUENTES',
      questions: 'QUESTIONS',
      faqServices: 'Quels services proposez-vous ?',
      faqServicesAnswer: 'Je propose une gestion complète d\'infrastructure IT, du conseil en cybersécurité, de l\'administration système et des services de sécurité réseau.',
      faqTimeline: 'Quel est votre délai typique de projet ?',
      faqTimelineAnswer: 'Les délais de projet varient selon la complexité. Les implémentations simples prennent 1-2 semaines, tandis que les projets d\'infrastructure complexes peuvent prendre 2-3 mois.',
      faqInternational: 'Travaillez-vous avec des clients internationaux ?',
      faqInternationalAnswer: 'Oui, je travaille avec des clients du monde entier. Je peux fournir un support et une consultation à distance pour les projets internationaux.',
      faqProcess: 'Quel est votre processus de développement ?',
      faqProcessAnswer: 'Mon processus inclut une consultation initiale, une analyse des exigences, une planification, une implémentation, des tests et un support continu.',
      readyToStart: 'Prêt à commencer ?',
      startDescription: 'Discutons de vos exigences de projet et créons quelque chose d\'incroyable ensemble.',
      startProject: 'Démarrer un projet',
      scheduleCall: 'Planifier un appel'
    }
  },
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      projects: 'Projects',
      skills: 'Skills',
      contact: 'Contact'
    },
    home: {
      welcome: 'WELCOME TO MY PORTFOLIO',
      title: 'YOUSSEF GUERNIOU',
      subtitle: 'Systems and Network Administrator passionate about cybersecurity and cloud technologies. Specialized in IT infrastructure management and securing digital environments.',
      viewProjects: 'View my projects',
      downloadCV: 'Download CV',
      readyToCollaborate: 'Ready to collaborate?',
      collaborateText: 'I\'m always open to new opportunities and innovative projects. Don\'t hesitate to contact me to discuss your needs.',
      getInTouch: 'Get in touch',
      viewMyWork: 'View my work',
      startProject: 'Start a project',
      viewGitHub: 'View GitHub'
    },
    about: {
      title: 'ABOUT',
      subtitle: 'Passionate about cybersecurity and system administration, I transform technical challenges into innovation opportunities. My goal: secure and optimize tomorrow\'s digital infrastructures.',
      myStory: 'My Story',
      storyText1: 'It all started with a natural curiosity to understand how computer systems work. From a simple user, I became a support technician, then a systems and network administrator.',
      storyText2: 'Today, I specialize in cybersecurity, a field that perfectly combines my passion for technology and my desire to protect organizations against digital threats.',
      myValues: 'My Values',
      securityFirst: 'Security First',
      securityDesc: 'Protecting systems and data is my absolute priority. Every solution I develop integrates cybersecurity best practices.',
      continuousInnovation: 'Continuous Innovation',
      innovationDesc: 'I constantly stay up to date with the latest technologies and methodologies to offer modern and efficient solutions.',
      technicalExcellence: 'Technical Excellence',
      excellenceDesc: 'I strive for excellence in every project, optimizing system performance and reliability.',
      collaboration: 'Collaboration',
      collaborationDesc: 'I believe in teamwork and effective communication to succeed in complex and ambitious projects.',
      myJourney: 'My Journey',
      journey2021: 'Beginning of the Journey',
      journey2021Desc: 'First steps in IT support at BIOGROUP, discovery of the professional IT world.',
      journey2023: 'Technical Evolution',
      journey2023Desc: 'Transition to systems and network administration at IMX France, technical skills development.',
      journey2024: 'Cybersecurity Specialization',
      journey2024Desc: 'Start of Master\'s in Cybersecurity, deepening knowledge in computer security.',
      journey2026: 'Future Goal',
      journey2026Desc: 'Cybersecurity expert, senior consultant in information systems security.'
    },
    projects: {
      showcase: 'MY PROJECTS',
      title: 'Project Portfolio',
      subtitle: 'Discover my achievements in web development and IT infrastructure management.',
      description: 'Description',
      features: 'MAIN FEATURES',
      techStack: 'TECHNOLOGY STACK',
      viewCode: 'VIEW CODE',
      viewLive: 'VIEW LIVE',
      wantToCollaborate: 'Want to collaborate?',
      collaborateText: 'I\'m always open to new projects and collaboration opportunities.',
      startProject: 'Start a project',
      viewGitHub: 'View GitHub'
    },
    skills: {
      expertise: 'TECHNICAL EXPERTISE',
      title: 'Skills & Technologies',
      subtitle: 'A comprehensive overview of my technical skills, tools and expertise in system administration, networking and cybersecurity domains.',
      contactInfo: 'CONTACT INFORMATION',
      technicalSkills: 'TECHNICAL SKILLS',
      softSkills: 'SOFT SKILLS',
      experience: 'PROFESSIONAL EXPERIENCE',
      education: 'EDUCATION & TRAINING',
      interests: 'INTERESTS',
      cloud: 'Cloud',
      networks: 'Networks',
      security: 'Security',
      administration: 'Administration',
      monitoring: 'Monitoring',
      problemSolving: 'Problem Solving',
      teamCollaboration: 'Team Collaboration',
      adaptability: 'Adaptability',
      systemAdmin: 'Systems and Network Administrator - APPRENTICESHIP',
      itSupport: 'IT Support Technician',
      since2023: 'Since 2023',
      from2021to2023: 'From 2021 to 2023',
      masterCybersecurity: 'MASTER - Cybersecurity',
      bachelorSystems: 'BACHELOR - Systems, Networks and Cloud',
      from2024to2026: 'From 2024 to 2026',
      from2023to2024: 'From 2023 to 2024',
      reading: 'Reading',
      travel: 'Travel',
      glpiDeployment: 'GLPI deployment: Installation, configuration and management',
      firewallSetup: 'Firewall implementation and ESET antivirus administration',
      virtualization: 'Management of virtualized environments via vSphere / vCenter',
      nasMonitoring: 'NAS network monitoring with SpaceObserver',
      vpnSetup: 'Installation and administration of StormShield VPN',
      gpoImplementation: 'Creation and implementation of GPOs on Active Directory',
      siemSetup: 'SIEM implementation: Security Onion',
      technicalSupport: 'Technical assistance and support for IT hardware',
      ticketing: 'Work organization via a ticketing service',
      areas: ['Windows', 'Linux', 'DevOps', 'Cloud', 'Project Management'],
      ipAddressing: 'IP Addressing',
      firewall: 'Firewall',
      vulnerabilityAnalysis: 'Vulnerability Analysis',
      windowsServer: 'Windows Server',
      linuxUbuntuDebian: 'Linux (Ubuntu, Debian)',
      englishLevel: 'English - Level B2'
    },
    contact: {
      title: 'Contact',
      subtitle: 'Contact me',
      contactText: 'I\'m always open to new opportunities and innovative projects.',
      name: 'Name',
      email: 'Email',
      message: 'Message',
      send: 'Send',
      location: 'Paris, France',
      phone: '+33 6 20 01 95 27',
      emailAddress: 'youssef.guerniou@proton.me',
      getInTouch: 'GET IN TOUCH',
      letsConnect: 'Let\'s Connect',
      connectDescription: 'Ready to start a project or just want to chat? I\'m always excited to hear about new opportunities and interesting ideas.',
      sendMessage: 'Send a Message',
      connectWithMe: 'Connect With Me',
      quickStats: 'Quick Stats',
      projectsCompleted: 'Projects Completed',
      happyClients: 'Happy Clients',
      yearsExperience: 'Years Experience',
      responseTime: 'Response Time',
      skillsRadar: 'SKILLS RADAR',
      keyAchievements: 'KEY ACHIEVEMENTS',
      liveStatus: 'REAL-TIME STATUS',
      funFacts: 'FUN FACTS',
      fact1: 'The first computer virus was created in 1986 and was called "Brain"',
      factCategory: 'Cybersecurity History',
      coffeeConsumed: 'Cups of Coffee Consumed',
      bugsToday: 'Bugs Today',
      funQuote: 'Code is like humor. When it needs to explain itself, it\'s bad.',
      quoteAuthor: 'Cory House',
      dailyChallenge: 'Daily Challenge',
      challengeText: 'Find the hidden bug on this page!',
      acceptChallenge: 'Accept the Challenge',
      easterEgg: 'Click for a surprise!',
      // FAQ translations
      frequentlyAsked: 'FREQUENTLY ASKED',
      questions: 'QUESTIONS',
      faqServices: 'What services do you offer?',
      faqServicesAnswer: 'I offer comprehensive IT infrastructure management, cybersecurity consulting, system administration, and network security services.',
      faqTimeline: 'What is your typical project timeline?',
      faqTimelineAnswer: 'Project timelines vary depending on complexity. Simple implementations take 1-2 weeks, while complex infrastructure projects can take 2-3 months.',
      faqInternational: 'Do you work with international clients?',
      faqInternationalAnswer: 'Yes, I work with clients worldwide. I can provide remote support and consultation for international projects.',
      faqProcess: 'What is your development process?',
      faqProcessAnswer: 'My process includes initial consultation, requirements analysis, planning, implementation, testing, and ongoing support.',
      readyToStart: 'Ready to Start?',
      startDescription: 'Let\'s discuss your project requirements and create something amazing together.',
      startProject: 'Start a Project',
      scheduleCall: 'Schedule a Call'
    }
  },
  ko: {
    nav: {
      home: '홈',
      about: '소개',
      projects: '프로젝트',
      skills: '기술',
      contact: '연락처'
    },
    home: {
      welcome: '내 포트폴리오에 오신 것을 환영합니다',
      title: 'YOUSSEF GUERNIOU',
      subtitle: '사이버보안과 클라우드 기술에 열정을 가진 시스템 및 네트워크 관리자. IT 인프라 관리 및 디지털 환경 보안 전문.',
      viewProjects: '내 프로젝트 보기',
      downloadCV: '이력서 다운로드',
      readyToCollaborate: '협업할 준비가 되셨나요?',
      collaborateText: '저는 항상 새로운 기회와 혁신적인 프로젝트에 열려있습니다. 귀하의 요구사항에 대해 논의하기 위해 언제든 연락해 주세요.',
      getInTouch: '연락하기',
      viewMyWork: '내 작업 보기',
      startProject: '프로젝트 시작',
      viewGitHub: 'GitHub 보기'
    },
    about: {
      title: '소개',
      subtitle: '사이버보안과 시스템 관리에 열정을 가진 저는 기술적 도전을 혁신의 기회로 변화시킵니다. 목표：내일의 디지털 인프라를 보호하고 최적화하는 것。',
      myStory: '내 이야기',
      storyText1: '컴퓨터 시스템이 어떻게 작동하는지 이해하고자 하는 자연스러운 호기심에서 시작되었습니다。단순한 사용자에서 지원 기술자가 되었고, 그 다음 시스템 및 네트워크 관리자가 되었습니다。',
      storyText2: '오늘날 저는 사이버보안을 전문으로 하며, 이는 기술에 대한 열정과 조직을 디지털 위협으로부터 보호하고자 하는 욕구를 완벽하게 결합한 분야입니다。',
      myValues: '내 가치관',
      securityFirst: '보안 우선',
      securityDesc: '시스템과 데이터를 보호하는 것이 저의 절대적 우선순위입니다。제가 개발하는 모든 솔루션은 사이버보안 모범 사례를 통합합니다。',
      continuousInnovation: '지속적 혁신',
      innovationDesc: '저는 현대적이고 효율적인 솔루션을 제공하기 위해 최신 기술과 방법론을 지속적으로 업데이트합니다。',
      technicalExcellence: '기술적 우수성',
      excellenceDesc: '저는 모든 프로젝트에서 우수성을 추구하며, 시스템 성능과 신뢰성을 최적화합니다。',
      collaboration: '협업',
      collaborationDesc: '저는 복잡하고 야심찬 프로젝트에서 성공하기 위해 팀워크와 효과적인 의사소통을 믿습니다。',
      myJourney: '내 여정',
      journey2021: '여정의 시작',
      journey2021Desc: 'BIOGROUP에서 IT 지원의 첫 걸음, 전문 IT 세계의 발견。',
      journey2023: '기술적 진화',
      journey2023Desc: 'IMX France에서 시스템 및 네트워크 관리로 전환, 기술적 역량 개발。',
      journey2024: '사이버보안 전문화',
      journey2024Desc: '사이버보안 석사 시작, 컴퓨터 보안 지식 심화。',
      journey2026: '미래 목표',
      journey2026Desc: '사이버보안 전문가, 정보 시스템 보안 시니어 컨설턴트。'
    },
    projects: {
      showcase: '내 프로젝트',
      title: '프로젝트 포트폴리오',
      subtitle: '웹 개발 및 IT 인프라 관리에서의 성과를 확인하세요。',
      description: '설명',
      features: '주요 기능',
      techStack: '기술 스택',
      viewCode: '코드 보기',
      viewLive: '실시간 보기',
      wantToCollaborate: '협업하고 싶으신가요？',
      collaborateText: '저는 항상 새로운 프로젝트와 협업 기회에 열려있습니다。',
      startProject: '프로젝트 시작',
      viewGitHub: 'GitHub 보기'
    },
    skills: {
      expertise: '기술 전문성',
      title: '기술 및 도구',
      subtitle: '시스템 관리, 네트워킹 및 사이버보안 분야에서의 기술적 역량, 도구 및 전문성에 대한 포괄적인 개요。',
      contactInfo: '연락처 정보',
      technicalSkills: '기술적 역량',
      softSkills: '소프트 스킬',
      experience: '전문 경험',
      education: '교육 및 훈련',
      interests: '관심사',
      cloud: '클라우드',
      networks: '네트워크',
      security: '보안',
      administration: '관리',
      monitoring: '모니터링',
      problemSolving: '문제 해결',
      teamCollaboration: '팀 협업',
      adaptability: '적응력',
      systemAdmin: '시스템 및 네트워크 관리자 - 견습',
      itSupport: 'IT 지원 기술자',
      since2023: '2023년부터',
      from2021to2023: '2021년부터 2023년까지',
      masterCybersecurity: '석사 - 사이버보안',
      bachelorSystems: '학사 - 시스템, 네트워크 및 클라우드',
      from2024to2026: '2024년부터 2026년까지',
      from2023to2024: '2023년부터 2024년까지',
      reading: '독서',
      travel: '여행',
      glpiDeployment: 'GLPI 배포: 설치, 구성 및 관리',
      firewallSetup: '방화벽 구현 및 ESET 바이러스 백신 관리',
      virtualization: 'vSphere / vCenter를 통한 가상화 환경 관리',
      nasMonitoring: 'SpaceObserver를 사용한 NAS 네트워크 모니터링',
      vpnSetup: 'StormShield VPN 설치 및 관리',
      gpoImplementation: 'Active Directory에서 GPO 생성 및 구현',
      siemSetup: 'SIEM 구현: Security Onion',
      technicalSupport: 'IT 하드웨어 기술 지원 및 지원',
      ticketing: '티켓팅 서비스를 통한 작업 조직',
      areas: ['Windows', 'Linux', 'DevOps', 'Cloud', '프로젝트 관리'],
      ipAddressing: 'IP 주소 지정',
      firewall: '방화벽',
      vulnerabilityAnalysis: '취약점 분석',
      windowsServer: 'Windows Server',
      linuxUbuntuDebian: 'Linux (Ubuntu, Debian)',
      englishLevel: '영어 - B2 레벨'
    },
    contact: {
      title: '연락처',
      subtitle: '연락하기',
      contactText: '저는 항상 새로운 기회와 혁신적인 프로젝트에 열려있습니다。',
      name: '이름',
      email: '이메일',
      message: '메시지',
      send: '보내기',
      location: '파리, 프랑스',
      phone: '+33 6 20 01 95 27',
      emailAddress: 'youssef.guerniou@proton.me',
      getInTouch: '연락하기',
      letsConnect: '연결해봅시다',
      connectDescription: '프로젝트를 시작하거나 단순히 대화하고 싶으신가요？저는 항상 새로운 기회와 흥미로운 아이디어에 대해 듣는 것을 기대합니다。',
      sendMessage: '메시지 보내기',
      connectWithMe: '저와 연결하기',
      quickStats: '빠른 통계',
      projectsCompleted: '완료된 프로젝트',
      happyClients: '만족한 고객',
      yearsExperience: '경험 연수',
      responseTime: '응답 시간',
      skillsRadar: '기술 레이더',
      keyAchievements: '주요 성과',
      liveStatus: '실시간 상태',
      funFacts: '재미있는 사실',
      fact1: '최초의 컴퓨터 바이러스는 1986년에 생성되었으며 "Brain"이라고 불렸습니다',
      factCategory: '사이버보안 역사',
      coffeeConsumed: '소비된 커피',
      bugsToday: '오늘의 버그',
      funQuote: '코드는 유머와 같습니다。스스로 설명해야 할 때는 나쁜 것입니다。',
      quoteAuthor: 'Cory House',
      dailyChallenge: '일일 도전',
      challengeText: '이 페이지에서 숨겨진 버그를 찾아보세요！',
      acceptChallenge: '도전 수락',
      easterEgg: '클릭하면 놀라움이！',
      // FAQ translations
      frequentlyAsked: '자주 묻는 질문',
      questions: '질문',
      faqServices: '어떤 서비스를 제공하시나요?',
      faqServicesAnswer: '포괄적인 IT 인프라 관리, 사이버보안 컨설팅, 시스템 관리 및 네트워크 보안 서비스를 제공합니다.',
      faqTimeline: '일반적인 프로젝트 일정은 어떻게 되나요?',
      faqTimelineAnswer: '프로젝트 일정은 복잡성에 따라 다릅니다. 간단한 구현은 1-2주, 복잡한 인프라 프로젝트는 2-3개월이 걸릴 수 있습니다.',
      faqInternational: '국제 고객과 함께 일하시나요?',
      faqInternationalAnswer: '네, 전 세계 고객과 함께 일합니다. 국제 프로젝트에 대한 원격 지원 및 컨설팅을 제공할 수 있습니다.',
      faqProcess: '개발 프로세스는 어떻게 되나요?',
      faqProcessAnswer: '제 프로세스는 초기 상담, 요구사항 분석, 계획, 구현, 테스트 및 지속적인 지원을 포함합니다.',
      readyToStart: '시작할 준비가 되셨나요?',
      startDescription: '프로젝트 요구사항에 대해 논의하고 함께 놀라운 것을 만들어봅시다.',
      startProject: '프로젝트 시작',
      scheduleCall: '통화 예약'
    }
  },
  ja: {
    nav: {
      home: 'ホーム',
      about: '自己紹介',
      projects: 'プロジェクト',
      skills: 'スキル',
      contact: 'お問い合わせ'
    },
    home: {
      welcome: '私のポートフォリオへようこそ',
      title: 'YOUSSEF GUERNIOU',
      subtitle: 'サイバーセキュリティとクラウド技術に情熱を持つシステム・ネットワーク管理者。ITインフラ管理とデジタル環境のセキュリティ専門。',
      viewProjects: 'プロジェクトを見る',
      downloadCV: '履歴書ダウンロード',
      readyToCollaborate: 'コラボレーションの準備はできていますか？',
      collaborateText: '私は常に新しい機会と革新的なプロジェクトにオープンです。ご要望について話し合うために、お気軽にお問い合わせください。',
      getInTouch: 'お問い合わせ',
      viewMyWork: '私の作品を見る',
      startProject: 'プロジェクト開始',
      viewGitHub: 'GitHubを見る'
    },
    about: {
      title: '自己紹介',
      subtitle: 'サイバーセキュリティとシステム管理に情熱を持つ私は、技術的課題を革新の機会に変えます。目標：明日のデジタルインフラを保護し最適化すること。',
      myStory: '私の物語',
      storyText1: 'コンピュータシステムがどのように動作するかを理解したいという自然な好奇心から始まりました。単純なユーザーからサポート技術者になり、その後システム・ネットワーク管理者になりました。',
      storyText2: '今日、私はサイバーセキュリティを専門としており、これは技術への情熱と組織をデジタル脅威から保護したいという願望を完璧に組み合わせた分野です。',
      myValues: '私の価値観',
      securityFirst: 'セキュリティ第一',
      securityDesc: 'システムとデータを保護することが私の絶対的な優先事項です。私が開発するすべてのソリューションはサイバーセキュリティのベストプラクティスを統合しています。',
      continuousInnovation: '継続的革新',
      innovationDesc: '私は現代的で効率的なソリューションを提供するために、最新の技術と方法論を常に更新しています。',
      technicalExcellence: '技術的卓越性',
      excellenceDesc: '私はすべてのプロジェクトで卓越性を追求し、システムのパフォーマンスと信頼性を最適化します。',
      collaboration: 'コラボレーション',
      collaborationDesc: '私は複雑で野心的なプロジェクトで成功するために、チームワークと効果的なコミュニケーションを信じています。',
      myJourney: '私の旅',
      journey2021: '旅の始まり',
      journey2021Desc: 'BIOGROUPでのITサポートの第一歩、専門IT世界の発見。',
      journey2023: '技術的進化',
      journey2023Desc: 'IMX Franceでのシステム・ネットワーク管理への移行、技術的スキルの開発。',
      journey2024: 'サイバーセキュリティ専門化',
      journey2024Desc: 'サイバーセキュリティ修士課程開始、コンピュータセキュリティ知識の深化。',
      journey2026: '将来の目標',
      journey2026Desc: 'サイバーセキュリティ専門家、情報システムセキュリティシニアコンサルタント。'
    },
    projects: {
      showcase: '私のプロジェクト',
      title: 'プロジェクトポートフォリオ',
      subtitle: 'ウェブ開発とITインフラ管理での成果をご覧ください。',
      description: '説明',
      features: '主要機能',
      techStack: '技術スタック',
      viewCode: 'コードを見る',
      viewLive: 'ライブで見る',
      wantToCollaborate: 'コラボレーションしたいですか？',
      collaborateText: '私は常に新しいプロジェクトとコラボレーションの機会にオープンです。',
      startProject: 'プロジェクト開始',
      viewGitHub: 'GitHubを見る'
    },
    skills: {
      expertise: '技術専門性',
      title: 'スキルと技術',
      subtitle: 'システム管理、ネットワーキング、サイバーセキュリティ分野での技術的スキル、ツール、専門性の包括的概要。',
      contactInfo: '連絡先情報',
      technicalSkills: '技術的スキル',
      softSkills: 'ソフトスキル',
      experience: '専門経験',
      education: '教育と訓練',
      interests: '興味',
      cloud: 'クラウド',
      networks: 'ネットワーク',
      security: 'セキュリティ',
      administration: '管理',
      monitoring: 'モニタリング',
      problemSolving: '問題解決',
      teamCollaboration: 'チームコラボレーション',
      adaptability: '適応性',
      systemAdmin: 'システム・ネットワーク管理者 - 見習い',
      itSupport: 'ITサポート技術者',
      since2023: '2023年から',
      from2021to2023: '2021年から2023年まで',
      masterCybersecurity: '修士 - サイバーセキュリティ',
      bachelorSystems: '学士 - システム、ネットワーク、クラウド',
      from2024to2026: '2024年から2026年まで',
      from2023to2024: '2023年から2024年まで',
      reading: '読書',
      travel: '旅行',
      glpiDeployment: 'GLPI展開：インストール、設定、管理',
      firewallSetup: 'ファイアウォール実装とESETアンチウイルス管理',
      virtualization: 'vSphere / vCenterによる仮想化環境管理',
      nasMonitoring: 'SpaceObserverによるNASネットワーク監視',
      vpnSetup: 'StormShield VPNのインストールと管理',
      gpoImplementation: 'Active DirectoryでのGPO作成と実装',
      siemSetup: 'SIEM実装：Security Onion',
      technicalSupport: 'ITハードウェアの技術支援とサポート',
      ticketing: 'チケットサービスによる作業組織化',
      areas: ['Windows', 'Linux', 'DevOps', 'Cloud', 'プロジェクト管理'],
      ipAddressing: 'IPアドレッシング',
      firewall: 'ファイアウォール',
      vulnerabilityAnalysis: '脆弱性分析',
      windowsServer: 'Windows Server',
      linuxUbuntuDebian: 'Linux (Ubuntu, Debian)',
      englishLevel: '英語 - B2レベル'
    },
    contact: {
      title: 'お問い合わせ',
      subtitle: 'お問い合わせ',
      contactText: '私は常に新しい機会と革新的なプロジェクトにオープンです。',
      name: '名前',
      email: 'メール',
      message: 'メッセージ',
      send: '送信',
      location: 'パリ、フランス',
      phone: '+33 6 20 01 95 27',
      emailAddress: 'youssef.guerniou@proton.me',
      getInTouch: 'お問い合わせ',
      letsConnect: 'つながりましょう',
      connectDescription: 'プロジェクトを始める準備ができているか、単に話したいだけですか？私は常に新しい機会と興味深いアイデアについて聞くことを楽しみにしています。',
      sendMessage: 'メッセージを送る',
      connectWithMe: '私とつながる',
      quickStats: 'クイック統計',
      projectsCompleted: '完了したプロジェクト',
      happyClients: '満足したクライアント',
      yearsExperience: '経験年数',
      responseTime: '応答時間',
      skillsRadar: 'スキルレーダー',
      keyAchievements: '主要な成果',
      liveStatus: 'リアルタイムステータス',
      funFacts: '面白い事実',
      fact1: '最初のコンピュータウイルスは1986年に作成され、「Brain」と呼ばれていました',
      factCategory: 'サイバーセキュリティの歴史',
      coffeeConsumed: '消費されたコーヒー',
      bugsToday: '今日のバグ',
      funQuote: 'コードはユーモアのようなものです。自分自身を説明する必要があるときは悪いものです。',
      quoteAuthor: 'Cory House',
      dailyChallenge: '日々の挑戦',
      challengeText: 'このページで隠されたバグを見つけてください！',
      acceptChallenge: '挑戦を受け入れる',
      easterEgg: 'クリックすると驚きが！',
      // FAQ translations
      frequentlyAsked: 'よくある質問',
      questions: '質問',
      faqServices: 'どのようなサービスを提供していますか？',
      faqServicesAnswer: '包括的なITインフラ管理、サイバーセキュリティコンサルティング、システム管理、ネットワークセキュリティサービスを提供しています。',
      faqTimeline: '一般的なプロジェクトのタイムラインはどのくらいですか？',
      faqTimelineAnswer: 'プロジェクトのタイムラインは複雑さによって異なります。簡単な実装は1-2週間、複雑なインフラプロジェクトは2-3ヶ月かかる場合があります。',
      faqInternational: '国際的なクライアントと一緒に仕事をしていますか？',
      faqInternationalAnswer: 'はい、世界中のクライアントと一緒に仕事をしています。国際プロジェクトのリモートサポートとコンサルティングを提供できます。',
      faqProcess: '開発プロセスはどのようになっていますか？',
      faqProcessAnswer: '私のプロセスは初期コンサルテーション、要件分析、計画、実装、テスト、継続的なサポートを含みます。',
      readyToStart: '始める準備はできていますか？',
      startDescription: 'プロジェクトの要件について話し合い、一緒に素晴らしいものを作りましょう。',
      startProject: 'プロジェクト開始',
      scheduleCall: '通話予約'
    }
  }
}

interface LanguageProviderProps {
  children: ReactNode
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr')

  const t = (key: string): string => {
    const keys = key.split('.')
    let value: any = translations[language]
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k]
      } else {
        return key // Return the key if translation not found
      }
    }
    
    return typeof value === 'string' ? value : key
  }

  const value = {
    language,
    setLanguage,
    t
  }

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 